[build]
  base = "24001182-km7-Dav-CarRen-ch3/backend"  # Make sure this path is correct
  command = "npm install"
  # Remove the publish line if you're not serving static files
  # publish = "public"  # Remove or comment this line if not needed

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/carHandler"
  status = 200
